#!/bin/bash

# This file should contain $API_KEY and $CHAT_ID
source /etc/telegram/key

URL="https://api.telegram.org/bot$API_KEY/sendMessage"
curl -s -d "chat_id=$CHAT_ID&disable_web_page_preview=1&text=$1" $URL >/dev/null
