#!/bin/bash

REMOTE_VER="$(curl -s 'https://download.veloren.net/version/linux/aarch64/nightly')"
REMOTE_DIR="/usr/veloren"
FORCE_UPDATE="false"
FILENAME="veloren-aarch64"

mkdir -p $REMOTE_DIR

while test "$#" -gt 0; do
  case "$1" in
   -f|--force) 
        FORCE_UPDATE="true"
        shift
        ;;
    *)
        break
        ;;
  esac
done

if [[ $REMOTE_VER = "$(cat $REMOTE_DIR/version)" && $FORCE_UPDATE == "false" ]]; then
    echo -e "\e[32m\e[1mYour server is up-to-date :)\e[0m"
else
    echo $REMOTE_VER > $REMOTE_DIR/version

    (cd $REMOTE_DIR && curl -L -o $FILENAME --connect-timeout 30 \
        --max-time 30 \
        --retry 300 \
        --retry-delay 5 \
        'https://download.veloren.net/latest/linux/aarch64/nightly')

    (cd $REMOTE_DIR && unzip -qo $FILENAME)
    (cd $REMOTE_DIR && rm -rf $FILENAME)

    systemctl restart veloren-server.service

    echo -e "\e[32m\e[1mSuccessfully updated server to latest version ($REMOTE_VER)\e[0m"
fi



