#!/bin/bash

REMOTE_VER="$(curl -s 'https://download.veloren.net/version/linux-aarch64')"
REMOTE_DIR="/usr/veloren"

mkdir -p $REMOTE_DIR 

if [[ $REMOTE_VER = "$(cat $REMOTE_DIR/version)" ]]; then
    echo -e "\e[32m\e[1mYour server is up-to-date :)\e[0m"
else
    echo $REMOTE_VER > $REMOTE_DIR/version

    (cd $REMOTE_DIR && curl -LO --connect-timeout 30 \
        --max-time 30 \
        --retry 300 \
        --retry-delay 5 \
        'http://download.veloren.net/latest/linux-aarch64') 

    (cd $REMOTE_DIR && unzip -qo linux-aarch64)
    (cd $REMOTE_DIR && rm -rf linux-aarch64)

    systemctl restart veloren-server.service

    echo -e "\e[32m\e[1mSuccessfully updated server to latest version ($REMOTE_VER)\e[0m"
fi


